# Generated by Django 4.1.2 on 2022-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.TextField(),
        ),
    ]
