<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-03 13:55
=======
# Generated by Django 4.1.2 on 2022-11-02 21:52
>>>>>>> 841ec8e568fe4de1d21756d05f58f0ed2c0027df

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
        ("videos", "0001_initial"),
>>>>>>> 841ec8e568fe4de1d21756d05f58f0ed2c0027df
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="videos.video",
            ),
        ),
    ]
